# Generated by Django 4.0.1 on 2022-07-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_bio_profile_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tle_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
